pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "root:/config"

// The wallpaper folder, the caches pibble generates beside it, and the
// client-side "xray" blur that stands in for compositor blur.
//
// Both halves live here together because they are produced by one scan: the
// blurred variant the launcher draws behind itself and the $BLUR a wallpaper
// command receives are the same file, generated by the same background pass
// that generates thumbnails.
Singleton {
    id: root

    // Injected by LauncherWindow, which is the only thing that knows which
    // output the launcher actually mapped onto. Until it exists (and if it
    // never does) the primary output stands in, so the very first scan is
    // still keyed on real geometry.
    property var screen: Quickshell.screens.length > 0 ? Quickshell.screens[0] : null
    // Also injected by LauncherWindow: a wallpaper applied while the launcher
    // is up must not swap the backdrop out from under it (see syncXrayShown).
    property bool launcherShown: false

    readonly property string dir: SystemInfo.expandHome(Settings.wallpaperDir)

    // Each entry: path|thumb|blurred|pan|proxy. All generated variants point
    // into cacheRoot, keyed by a hash of the source path (stable across
    // renames of unrelated files, safe across multiple wallpaperDirs);
    // <stem>blurred.<ext> next to the source is still honored as a
    // user-supplied override of the blurred one.
    //
    // The cache is split by the *shape* of what it holds, not by which pane
    // reads it - one file often serves two - so a variant's directory says
    // what it is:
    //
    //   thumbnails/crops   480x270 center crop, every type
    //   thumbnails/wide    uncropped, source aspect, <=1920x1080
    //   thumbnails/clips   the clipboard's own thumbs (Clipboard owns these)
    //   blurred            output-sized and pre-blurred, see the xray block
    //   proxies            preview-res video re-encodes, see below
    //
    // thumb is what a grid tile draws and pan is what the carousel slides a
    // fixed window across, so an image's thumb is its crop and its pan is its
    // wide still. A video's crop is cut from its wide still (Image can't
    // decode the source file), and until the generation pass writes it the
    // wide still stands in as the thumb too.
    //
    // proxy is what the preview players decode instead of the source
    // (WallpaperVideoPool; the desktop's own wallpaper command always gets the
    // original). A hardware decoder's frame pool lives in VRAM and scales with
    // the coded size - ~300MiB resident for one 5K h264 file against ~35MiB at
    // 1920 - and the pool holds every video open at once, so the previews are
    // the one consumer that can't afford full-resolution sources. Capped at
    // the same 1920 as the wide still, and for the same reason: that is
    // already the resolution the carousel's box was judged to need, and still
    // and video handing over at different resolutions would read as a
    // sharpness step.
    //
    // One blurred image serves both uses: the launcher's own backdrop in
    // "xray" mode and the $BLUR the wallpaper command gets (see
    // applyWallpaper) - they're the same picture, so they're the same file.
    property var list: []
    // raw stdout of the scan `list` was last built from; see where it's compared
    property string lastScanText: ""
    // xrayCacheKey as of the last scan that landed. Only when it matches the
    // current one do the entries say anything about the backdrops the
    // launcher is actually after - before that (a scan from before the
    // output scale resolved, say) a missing entry means "not looked for
    // yet", not "not there".
    property string scanKey: ""
    property string lastMissingDir: ""
    // matugen chokes on/slow-decodes an animated source (and can't read
    // video at all); sample the cached static thumbnail instead when the
    // current wallpaper is a .gif or .mp4 (see Theme's matugen run). Falls back to
    // the raw path before the background scan has generated a thumbnail for
    // it yet.
    readonly property string matugenSource: {
        const w = root.list.find(x => x.path === Settings.currentWallpaper);
        return (w && (w.gif || w.video) && w.thumb) ? w.thumb : Settings.currentWallpaper;
    }
    // Started a tick late: this is called from change handlers on the very
    // properties the scan's own command binding reads (see xrayCacheKey), and
    // a binding is only guaranteed to have caught up by the time the next one
    // reads it - flipping `running` inline reliably ran the scan against the
    // previous geometry.
    function rescan(): void {
        scan.running = false;
        Qt.callLater(() => scan.running = true);
    }
    // cache entries the last scan found missing, and the re-scan armed to
    // pick them up as the background generation writes them - polled while
    // a pass holds the cache lock, armed once more on any change after it
    // exits (see where it's armed, in scan's output handler)
    property string generationMissing: ""
    Timer {
        id: generationRetry
        interval: 3000
        onTriggered: root.rescan()
    }
    Process {
        id: scan
        running: true
        // the xray parameters this run went looking for, captured at spawn
        // rather than read back when it finishes - the two can differ by a
        // whole scan (the output scale resolving is exactly that case), and
        // reading it late would claim a stale result was current
        property string scanKey: ""
        onRunningChanged: if (running) scanKey = root.xrayCacheKey
        command: ["bash", "-c", `
            cd "$1" || { echo NODIR; exit 0; }
            cachedir="$2"
            # First line: whether a generation pass currently holds the
            # cache lock (the flock taken in the generation script below).
            # The retry loop keys off this to keep polling while work is
            # still in flight - progress-between-scans alone can't tell a
            # slow entry (a 5K video in ffmpeg outlasts one retry interval)
            # from a cache that can never fill (no ffmpeg).
            gen=0
            [ -e "$cachedir/.generating" ] && ! flock -n "$cachedir/.generating" true && gen=1
            echo "GEN:$gen"
            shopt -s nullglob nocaseglob
            for f in *.png *.jpg *.jpeg *.webp *.gif *.mp4; do
                case "$f" in *blurred.*) continue ;; esac
                stem="\${f%.*}" ext="\${f##*.}"
                isvid=0; case "\${ext,,}" in mp4) isvid=1 ;; esac
                # a generated crop is true-color (png) even for a .gif source:
                # writing a single decoded frame back out as .gif would
                # quantize it to a 256-color palette, banding badly once
                # blurred. The source itself is still played back untouched.
                # A video's crop is cut from its wide still, a png already.
                # A .webp crop is written as png for a different reason: Qt
                # only decodes webp when the optional qtimageformats plugin is
                # installed, and this crop is what both the grid tile and the
                # wallpaper-changed notification's image point at - writing it
                # in a format the shell might not be able to read left both
                # blank (and the notification, whose card shape is chosen from
                # the image's aspect, demoted to a plain one).
                oext="$ext"; case "\${ext,,}" in gif|mp4|webp) oext="png" ;; esac
                # versioned like bkey below (r<n>): bump t<n> (here and in
                # the generation pass) whenever the crop recipe changes, so
                # stale entries fall out of the sweep instead of sticking
                # around under the old recipe until their source file happens
                # to change.
                key=$(printf '%s' "$PWD/$f|t6" | md5sum | cut -d' ' -f1)
                # the wide still, versioned the same way (p<n>) and for the
                # same reason as the two keys around it
                pkey=$(printf '%s' "$PWD/$f|p3" | md5sum | cut -d' ' -f1)
                # the blurred variant is the one cache entry that depends on
                # more than the source file, so the output geometry, the blur
                # and the recipe version go in its key too: a resized output,
                # a retuned kernel or a changed recipe then lands on a
                # different name, and the old one falls out of the sweep
                # below like any other dead entry. Bump r<n> (here and in the
                # generation pass) whenever the ffmpeg command changes.
                bkey=$(printf '%s' "$PWD/$f|$3|$4|r6" | md5sum | cut -d' ' -f1)
                # the preview proxy, versioned the same way (x<n>): bump it
                # (here and in the generation pass) when the ffmpeg recipe
                # changes
                vkey=$(printf '%s' "$PWD/$f|x1" | md5sum | cut -d' ' -f1)
                # the wide still is a jpeg for an image and a png for a video -
                # see the two calls in the generation pass
                wide="$cachedir/thumbnails/wide/$pkey.jpg"
                [ "$isvid" = "1" ] && wide="$cachedir/thumbnails/wide/$pkey.png"
                thumb="" blur="" pan="" pxy=""
                # only trust caches newer than the source image
                [ "$wide" -nt "$f" ] && pan="$wide"
                if [ "$isvid" = "1" ]; then
                    # Image can't decode the source file at all, so the wide
                    # still stands in for the grid tile - both stay empty
                    # until the generation pass takes it - and the crop cut
                    # from it (see the generation pass for why one exists)
                    # takes over once it lands
                    thumb="$pan"
                    [ "$cachedir/thumbnails/crops/$key.$oext" -nt "$f" ] && thumb="$cachedir/thumbnails/crops/$key.$oext"
                    [ "$cachedir/proxies/$vkey.mp4" -nt "$f" ] && pxy="$cachedir/proxies/$vkey.mp4"
                else
                    # a fresh image/gif stands in as its own tile (the Image
                    # element decodes it directly, just slowly) until the crop
                    # lands
                    thumb="$PWD/$f"
                    [ "$cachedir/thumbnails/crops/$key.$oext" -nt "$f" ] && thumb="$cachedir/thumbnails/crops/$key.$oext"
                fi
                [ "$cachedir/blurred/$bkey.png" -nt "$f" ] && blur="$cachedir/blurred/$bkey.png"
                [ -e "\${stem}blurred.$ext" ] && blur="$PWD/\${stem}blurred.$ext"
                printf '%s|%s|%s|%s|%s\\n' "$PWD/$f" "$thumb" "$blur" "$pan" "$pxy"
            done | sort`, "_", root.dir, SystemInfo.cacheRoot,
            root.xraySize.width + "x" + root.xraySize.height, String(root.xrayCacheSigma)]
        stdout: StdioCollector {
            onStreamFinished: {
                root.scanKey = scan.scanKey;
                if (text.trim() === "NODIR") {
                    root.lastScanText = text;
                    root.list = [];
                    if (root.lastMissingDir !== root.dir) {
                        root.lastMissingDir = root.dir;
                        Notifier.error(Strings.tr("Wallpaper folder not found"), root.dir + "\n\n" + Strings.tr("Change it in Settings > Pages > Wallpapers path."));
                    }
                    return;
                }
                root.lastMissingDir = "";
                const generating = text.startsWith("GEN:1");
                // the GEN header reflects lock state, not folder content, so
                // it stays out of the body that lastScanText compares below -
                // a pass finishing must not read as "the folder changed"
                const body = text.slice(text.indexOf("\n") + 1);
                const walls = body.trim().split("\n").filter(l => l).map(l => {
                    const p = l.split("|");
                    return { path: p[0], thumb: p[1], blur: p[2] || "", pan: p[3] || "", proxy: p[4] || "", gif: /\.gif$/i.test(p[0]), video: /\.mp4$/i.test(p[0]) };
                });
                // Reassigning this array invalidates every tile's model entry,
                // which tears each delegate down and rebuilds it - re-creating
                // its ClippingRectangle render target and re-uploading its
                // thumbnail texture. A scan runs on every launcher open, and
                // the folder is almost never different between two of them, so
                // that cost was being paid mid-reveal for an identical result.
                // The scan's raw output is the canonical form of everything
                // `walls` is derived from, so an unchanged one means an
                // unchanged model: keep the existing array and its delegates.
                if (body !== root.lastScanText) {
                    root.lastScanText = body;
                    root.list = walls;
                }
                // Generate missing thumbnails (a full 5K image standing in as
                // its own thumbnail costs ~100ms to decode+upload), pan
                // sources and blurred
                // variants in the background; the next scan picks them up and
                // applying never has to blur synchronously. Also sweeps cache
                // entries whose source wallpaper is gone - runs every scan
                // (not just when something's missing) so deletions get cleaned
                // up promptly.
                //
                // Both consumers of the blurred variant gate it the same way:
                // it's wanted if the launcher draws it (xray mode) or the
                // wallpaper command asks for it ($BLUR). The geometry check is
                // what holds it back until the output scale it's keyed on has
                // resolved.
                const wantBlur = (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR"))
                    && root.xraySize.width > 0 && root.xrayCacheSigma > 0;
                // proxies are only for the live previews, so nothing asks for
                // them while those are off. Existing ones are kept (their keys
                // are source-only, so the sweep still knows them), and turning
                // previews back on generates the rest on the next scan.
                const wantProxy = Settings.wallpaperLive;
                // current wallpaper first: on a cold cache its backdrop is the
                // one thing the launcher needs before any other entry, and a
                // big folder is minutes of work to get through
                const paths = walls.map(w => w.path);
                const cur = paths.indexOf(Settings.currentWallpaper);
                const order = cur > 0 ? [paths[cur]].concat(paths.slice(0, cur), paths.slice(cur + 1)) : paths;
                // Arm a follow-up scan whenever anything is still missing:
                // the pass below is fire-and-forget, so nothing reports when
                // its output lands, and until a scan sees the files the
                // launcher keeps falling back (a sharp thumbnail-less video
                // tile, a live-blurred backdrop). While a pass still holds
                // the cache lock (the scan's GEN header) keep polling
                // unconditionally - one slow entry (a 5K video in ffmpeg)
                // can outlast the retry interval with nothing landing, and
                // "no progress since last scan" used to kill the loop right
                // there, stranding whatever the pass wrote afterwards until
                // the next open. With no pass running, the comparison
                // against the last missing set is what keeps a cache that
                // *can't* be filled - no ffmpeg - from scanning on a
                // loop: unchanged-and-idle means nothing more is coming.
                // a video whose thumb still points at its pan entry is one
                // whose crop hasn't landed yet (see the scan's isvid branch)
                const missing = walls.filter(w => w.thumb === "" || w.pan === "" || (w.video && w.thumb === w.pan) || (wantBlur && w.blur === "") || (wantProxy && w.video && w.proxy === "")).map(w => w.path).join("|");
                if (missing !== "" && (generating || missing !== root.generationMissing))
                    generationRetry.restart();
                root.generationMissing = missing;
                Quickshell.execDetached(["bash", "-c", `
                    # The last four arguments carry the two alerts already
                    # translated: the shell's language is a QML question, and
                    # passing the finished strings in as argv beats trying to
                    # interpolate them into a script body
                    walldir="$1" cachedir="$2" gb="$3" alerts="$4" xgeom="$5" xsigma="$6" gp="$7"; shift 7
                    # shifted first rather than read as the 7th-10th
                    # positionals directly: this script is a QML template
                    # literal, where a braced positional past $9 would be read
                    # as a JS substitution rather than a shell one
                    ffsum="$1" ffbody="$2" encsum="$3" encbody="$4"; shift 4
                    mkdir -p "$cachedir/thumbnails/crops" "$cachedir/thumbnails/wide" "$cachedir/blurred" "$cachedir/proxies"
                    # Layouts this cache has had before: wallpapers/ + xray/
                    # (from when the backdrop had a cache of its own, before
                    # thumbnails/ and blurred/ moved up next to the
                    # clipboard's), then a flat thumbnails/ beside a pan/ -
                    # both since split by shape into the two directories
                    # above. Regenerating an entry is a second or so, so the
                    # old trees just go rather than being migrated. The find
                    # is what clears the flat layout without touching the
                    # subdirectories that replaced it.
                    rm -rf "$cachedir/wallpapers" "$cachedir/xray" "$cachedir/pan"
                    find "$cachedir/thumbnails" -maxdepth 1 -type f -delete 2>/dev/null
                    # one generation pass at a time: scans are cheap and fire
                    # on every open, and two passes racing on the same cache
                    # entry is duplicated ffmpeg work at best
                    exec 9>"$cachedir/.generating"
                    flock -n 9 || exit 0
                    warnedFfmpeg=0
                    warnedEncoder=0
                    # Picked once rather than per wallpaper: the proxy's
                    # re-encode needs an H.264 encoder, and libx264 is absent
                    # from patent-free builds (Fedora's ffmpeg-free carries
                    # libopenh264 instead). Without a fallback the encode there
                    # failed silently and every preview went on decoding the
                    # source - exactly what the proxy exists to avoid.
                    # openh264 has no CRF mode, so it gets a bitrate target
                    # instead; 8M at 1920 wide sits near the crf 18 the x264
                    # path asks for and is still a fraction of a 5K source.
                    encoders=$(ffmpeg -hide_banner -encoders 2>/dev/null)
                    venc=""
                    case "$encoders" in
                    *" libx264 "*) venc="-c:v libx264 -preset veryfast -crf 18" ;;
                    *" libopenh264 "*) venc="-c:v libopenh264 -b:v 8M" ;;
                    esac
                    live=""
                    for f in "$@"; do
                        b=$(basename "$f")
                        stem="\${b%.*}" ext="\${b##*.}"
                        isvid=0; case "\${ext,,}" in mp4) isvid=1 ;; esac
                        # see the matching oext note in the scan pass above
                        oext="$ext"; case "\${ext,,}" in gif|mp4|webp) oext="png" ;; esac
                        # see the matching key note in the scan pass above
                        key=$(printf '%s' "$f|t6" | md5sum | cut -d' ' -f1)
                        # see the matching pkey note in the scan pass above
                        pkey=$(printf '%s' "$f|p3" | md5sum | cut -d' ' -f1)
                        # see the matching bkey note in the scan pass above
                        bkey=$(printf '%s' "$f|$xgeom|$xsigma|r6" | md5sum | cut -d' ' -f1)
                        # see the matching vkey note in the scan pass above
                        vkey=$(printf '%s' "$f|x1" | md5sum | cut -d' ' -f1)
                        wide="$cachedir/thumbnails/wide/$pkey.jpg"
                        [ "$isvid" = "1" ] && wide="$cachedir/thumbnails/wide/$pkey.png"
                        live="$live $key $bkey $pkey $vkey"
                        needcrop=0 needblur=0 needwide=0 needproxy=0
                        [ "$cachedir/thumbnails/crops/$key.$oext" -nt "$f" ] || needcrop=1
                        [ "$wide" -nt "$f" ] || needwide=1
                        if [ "$gb" = "1" ]; then
                            [ "$cachedir/blurred/$bkey.png" -nt "$f" ] || [ -e "$walldir/\${stem}blurred.$ext" ] || needblur=1
                        fi
                        if [ "$gp" = "1" ] && [ "$isvid" = "1" ]; then
                            [ "$cachedir/proxies/$vkey.mp4" -nt "$f" ] || needproxy=1
                        fi
                        if [ "$needcrop" = "1" ] || [ "$needblur" = "1" ] || [ "$needwide" = "1" ] || [ "$needproxy" = "1" ]; then
                            if ! command -v ffmpeg >/dev/null 2>&1; then
                                if [ "$warnedFfmpeg" = "0" ] && [ "$alerts" = "1" ]; then
                                    warnedFfmpeg=1
                                    notify-send -a pibble -i system-software-install "$ffsum" "$ffbody"
                                fi
                            else
                                if [ "$isvid" = "1" ]; then
                                    # the wide still keeps the source aspect
                                    # rather than being cropped like the
                                    # images below: this frame is what the
                                    # carousel pans while the live video isn't
                                    # playing, and PreserveAspectCrop derives
                                    # its scale from the source aspect, so a
                                    # 16:9 still standing in for a video that
                                    # isn't 16:9 lands at a different crop than
                                    # the video itself - a visible zoom the
                                    # instant playback starts. Keeping the
                                    # source aspect makes the two identical in
                                    # any box.
                                    #
                                    # Capped at 1920 wide rather than a small
                                    # fixed size: this still doesn't only back
                                    # the grid's 240x135 tile (which
                                    # downscales at decode time regardless of
                                    # source size) - the carousel decodes the
                                    # same file at up to ~barHeight tall and
                                    # pans across it. A 480px-wide still
                                    # stretched to fill that box read as
                                    # blurrier than the live video it hands
                                    # off to. min() so a source already
                                    # narrower than 1920 isn't upscaled.
                                    #
                                    # flags=lanczos: ffmpeg's default scaler
                                    # is soft on top of an already-lossy
                                    # source, and unsharp claws a bit of that
                                    # back - a frozen compressed frame reads
                                    # blurrier than the same footage in
                                    # motion even at matched resolution
                                    # (motion masks the quantization/deblock
                                    # softness codecs lean on; playback via
                                    # VideoOutput never shows a truly static
                                    # frame the way this thumbnail does), so
                                    # this only narrows the gap, not closes it.
                                    #
                                    # in_color_matrix=bt709: swscale defaults
                                    # an untagged video to BT.601, but the Qt
                                    # video sink renders the same untagged
                                    # frames as BT.709 - so the still came out
                                    # measurably darker than the live preview
                                    # it hands over to (worst on dark footage:
                                    # -1.4% mean luma, halved by this flag),
                                    # which read as the video brightening the
                                    # moment playback started.
                                    [ "$needwide" = "1" ] && ffmpeg -y -v error -i "$f" -vframes 1 -vf "scale='min(1920,iw)':-1:flags=lanczos:in_color_matrix=bt709,unsharp=5:5:0.8:5:5:0.0" "$wide"
                                    # The preview proxy: what the pooled players
                                    # decode instead of the source (see the
                                    # proxies note at the top). Same 1920 cap as
                                    # the wide still, keeping the still->video
                                    # handover at matched resolution. A source
                                    # already inside the cap is remuxed rather
                                    # than re-encoded - same decoder footprint,
                                    # no generation loss - which also strips
                                    # audio like the transcode does (the players
                                    # are muted; carrying the track just makes
                                    # the pool open audio decoders to ignore).
                                    # Written to a temp name and moved: an
                                    # interrupted encode would otherwise leave a
                                    # newer-than-source file the scan trusts.
                                    # The temp's key-minus-extension misses
                                    # $live, so a crash's leftovers go with the
                                    # next sweep.
                                    if [ "$needproxy" = "1" ]; then
                                        vw=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of csv=p=0 "$f" 2>/dev/null | head -1)
                                        vtmp="$cachedir/proxies/$vkey.tmp.mp4"
                                        if [ -n "$vw" ] && [ "$vw" -le 1920 ] 2>/dev/null; then
                                            ffmpeg -y -v error -i "$f" -an -c:v copy -movflags +faststart "$vtmp"
                                        elif [ -n "$venc" ]; then
                                            # min() so an unprobeable source is
                                            # still never upscaled
                                            ffmpeg -y -v error -i "$f" -an -vf "scale='min(1920,iw)':-2:flags=lanczos" $venc -pix_fmt yuv420p -movflags +faststart "$vtmp"
                                        elif [ "$warnedEncoder" = "0" ] && [ "$alerts" = "1" ]; then
                                            # no H.264 encoder at all: the
                                            # preview still works, it just
                                            # decodes the source, so this is
                                            # worth saying once rather than
                                            # failing
                                            warnedEncoder=1
                                            notify-send -a pibble -i system-software-install "$encsum" "$encbody"
                                        fi
                                        if [ -s "$vtmp" ]; then mv "$vtmp" "$cachedir/proxies/$vkey.mp4"; else rm -f "$vtmp"; fi
                                    fi
                                    # The tile crop, cut from the wide still just
                                    # written rather than from the video, with the
                                    # recipe an image's crop gets below.
                                    # The wide still alone used to stand in as the
                                    # grid tile, decoded through sourceSize - and
                                    # Qt's decode-time downscale is visibly softer
                                    # than the GPU minification the live video
                                    # frame gets, so playback started with a
                                    # brightness/sharpness pop. A pre-scaled crop
                                    # decodes 1:1, exactly like an image tile's.
                                    # The center crop to 16:9 lands the same
                                    # framing PreserveAspectCrop cuts from the
                                    # video in the 16:9 tile box, so the handover
                                    # still moves nothing.
                                    #
                                    # force_original_aspect_ratio=increase then
                                    # crop is what ImageMagick spelled "-resize ^
                                    # -gravity center -extent": scale to cover the
                                    # box, then cut the centre out of it.
                                    if [ "$needcrop" = "1" ] && [ -e "$wide" ]; then
                                        ffmpeg -y -v error -i "$wide" -frames:v 1 -vf "scale=480:270:force_original_aspect_ratio=increase,crop=480:270" "$cachedir/thumbnails/crops/$key.$oext"
                                    fi
                                else
                                    # -frames:v 1: first frame only, so an
                                    # animated .gif source still yields a static
                                    # crop/blur (only the selected/centered
                                    # tile/window plays the source file itself)
                                    #
                                    # Both recipes composite onto black through a
                                    # lavfi color source rather than scaling
                                    # alone: ffmpeg carries alpha through to a png
                                    # and drops it outright on the way to a jpeg,
                                    # keeping the raw RGB underneath - which for a
                                    # transparent wallpaper is whatever the
                                    # encoder happened to leave there (white, on
                                    # the files this was measured against). Black
                                    # is what a transparent wallpaper actually
                                    # composites over on the desktop, so both the
                                    # tile and the still are flattened onto it.
                                    # scale2ref sizes that color source from the
                                    # scaled frame, so neither call has to know
                                    # the output geometry up front.
                                    [ "$needcrop" = "1" ] && ffmpeg -y -v error -f lavfi -i color=black -i "$f" -filter_complex "[1:v]scale=480:270:force_original_aspect_ratio=increase,crop=480:270[fg];[0:v][fg]scale2ref[bg][fg2];[bg][fg2]overlay=shortest=1" -frames:v 1 "$cachedir/thumbnails/crops/$key.$oext"
                                    # The wide still: the same frame
                                    # uncropped, bounded to the box a video's
                                    # already gets (see the ffmpeg call above), so
                                    # both types feed that strip the same picture
                                    # at the same quality. The two min()s only
                                    # ever shrink - a source already smaller
                                    # comes through as it is rather than being
                                    # upscaled into the cache.
                                    #
                                    # This exists purely to keep the decode off the
                                    # original: a 5K PNG costs ~280ms to decode
                                    # even asked for at 440px tall (unlike a JPEG,
                                    # PNG has no scaled decode path - the whole
                                    # thing is unpacked, then resized), and the
                                    # carousel pays that again for every cell that
                                    # wraps around the strip. At 1920 wide it is
                                    # ~30ms. JPEG, not the true-color PNG the
                                    # other variants are written as: nothing
                                    # downstream re-blurs this one, so there is no
                                    # banding to protect against, and the file
                                    # lands a fraction of the size.
                                    [ "$needwide" = "1" ] && ffmpeg -y -v error -f lavfi -i color=black -i "$f" -filter_complex "[1:v]scale='min(1920,iw)':'min(1080,ih)':force_original_aspect_ratio=decrease[fg];[0:v][fg]scale2ref[bg][fg2];[bg][fg2]overlay=shortest=1" -frames:v 1 -q:v 2 "$wide"
                                fi
                            fi
                        fi
                        # The blurred variant: the wallpaper as the compositor
                        # would blur it behind the launcher (see the xray
                        # block on root for where the numbers come from),
                        # which is also what the wallpaper command gets as
                        # $BLUR. A video goes through the still frame ffmpeg
                        # just wrote rather than the video itself.
                        #
                        # Cropped to the output's aspect so the launcher's
                        # PreserveAspectCrop has nothing left to crop and the
                        # blur lands at the sigma it was baked for. The crop
                        # rounds to a whole pixel of an image a quarter of the
                        # screen's size, which measures ~3 output pixels below
                        # the compositor's blur of the same wallpaper -
                        # deliberately left as is.
                        #
                        # gblur's sigma is ImageMagick's "-blur 0xsigma" (a 0
                        # radius there means "derive it from sigma", which is
                        # what gblur does anyway), and colorchannelmixer takes
                        # the same 3x3 the -color-matrix did, row per output
                        # channel. Measured against the ImageMagick recipe this
                        # replaced, the two land within 0.07% RMSE.
                        if [ "$needblur" = "1" ] && command -v ffmpeg >/dev/null 2>&1; then
                            bsrc="$f"
                            [ "$isvid" = "1" ] && bsrc="$wide"
                            xw="\${xgeom%x*}" xh="\${xgeom#*x}"
                            [ -e "$bsrc" ] && ffmpeg -y -v error -f lavfi -i color=black -i "$bsrc" -filter_complex "[1:v]scale=$xw:$xh:force_original_aspect_ratio=increase,crop=$xw:$xh,gblur=sigma=$xsigma,colorchannelmixer=rr=1.3937:rg=-0.3576:rb=-0.0361:gr=-0.1063:gg=1.1424:gb=-0.0361:br=-0.1063:bg=-0.3576:bb=1.4639[fg];[0:v][fg]scale2ref[bg][fg2];[bg][fg2]overlay=shortest=1" -frames:v 1 "$cachedir/blurred/$bkey.png"
                        fi
                    done
                    # clips/ is not swept here: the clipboard owns it, keys it
                    # by entry id rather than source path, and prunes it
                    # against clipsMax on its own scan
                    # proxies join the sweep unguarded: their keys are
                    # source-only (unlike blurred's geometry-keyed ones), so
                    # this pass always knows the live set even when it isn't
                    # generating any
                    for d in "$cachedir/thumbnails/crops" "$cachedir/thumbnails/wide" "$cachedir/blurred" "$cachedir/proxies"; do
                        # with nothing asking for blurred variants the keys
                        # this pass knows are not the ones those files were
                        # baked under, so leave them alone rather than
                        # sweeping the lot: asking again picks them straight
                        # back up, and any entry that really is dead by then
                        # goes with the first sweep that can tell.
                        [ "$d" = "$cachedir/blurred" ] && [ "$gb" != "1" ] && continue
                        for c in "$d"/*; do
                            [ -e "$c" ] || continue
                            k=$(basename "$c"); k="\${k%.*}"
                            case " $live " in *" $k "*) ;; *) rm -f "$c" ;; esac
                        done
                    done`, "_", root.dir, SystemInfo.cacheRoot, wantBlur ? "1" : "0", Settings.alertEnabled("missingDeps") ? "1" : "0",
                    root.xraySize.width + "x" + root.xraySize.height, String(root.xrayCacheSigma), wantProxy ? "1" : "0",
                    Strings.tr("ffmpeg not found"),
                    Strings.tr("ffmpeg is used to generate video wallpaper thumbnails and blurred previews - install it for sharper, faster previews."),
                    Strings.tr("No H.264 encoder found"),
                    Strings.tr("ffmpeg has no H.264 encoder (libx264 or libopenh264), so video wallpaper previews decode the source file instead of a smaller proxy.")].concat(order));
            }
        }
    }

    // ---------- the blurred wallpaper ----------
    // The client-side blur ("xray", see Settings.bgBlur) draws the wallpaper
    // blurred into the cache alongside its thumbnail (see scan), rather
    // than blurring live every time the launcher opens. niri's own xray mode
    // works the same way, and for the same reason: the wallpaper is the only
    // thing being blurred and it almost never changes, so blurring it once
    // and reusing the result is free from then on. Live blur, by contrast,
    // pays a shader compile plus a screen-sized offscreen pass on the first
    // frame after the layer surface maps - long enough to watch the backdrop
    // turn up late behind a grow reveal. The same file is what a wallpaper
    // command gets as $BLUR (see LauncherWindow.applyWallpaper).
    //
    // The kernel is cloned from niri's defaults (`blur { passes 3; offset 3;
    // noise 0.02; saturation 1.5 }`). Its dual kawase chain - 3 downsample
    // then 3 upsample passes, each tapping at `offset` halves of a
    // destination pixel with the 5/8-tap kernels in
    // src/render_helpers/shaders/blur_{down,up}.frag - has an impulse
    // response indistinguishable from a gaussian of sigma 19.17: simulating
    // the chain and blurring a hard edge with `-blur 0x19.17` both spread it
    // over exactly 50px, 10% to 90%. So one gaussian is the whole chain.
    //
    // Saturation is niri's postprocess step: a mix toward Rec.709 luma,
    // applied to the blurred result in the same non-linear sRGB the blur
    // itself runs in (its textures are plain 8-bit ABGR, no linearization) -
    // which is what -color-matrix does here, and why nothing converts to
    // linear light first. Niri's noise step is the one part deliberately not
    // reproduced: it can't be baked in (this image is upscaled on the way to
    // the screen, so it would land as blotches rather than dither), and the
    // alternative - a noise tile drawn live over the backdrop - is a
    // full-screen texture that also shows as grain over the desktop whenever
    // there's no wallpaper baked to sit under it. The banding it would have
    // hidden is accepted instead.
    //
    // Sigma is niri's radius in *output* pixels. On a fractionally scaled
    // output the compositor hands anyone not speaking wp-fractional-scale a
    // rounded wl_output scale (niri reports 2 for a 1.25x output, which is
    // what a ShellScreen's devicePixelRatio - and a window's, until its
    // surface is mapped - comes back as), so dividing by that lands the blur
    // a long way off. A mapped surface is told the real fractional scale, so
    // that is what gets measured. See XrayScaleProbe.
    readonly property real xraySigma: 19.17
    // Baked at a quarter of the output's logical resolution. A blur this
    // wide leaves nothing that a quarter-rate sampling can't carry: against
    // the same blur done at full output resolution, the quarter-size bake
    // scaled back up measures 55dB PSNR - visually identical, at a sixteenth
    // of the ffmpeg run, the file size, the decode and the texture upload.
    readonly property int xrayScale: 4
    readonly property size xraySize: {
        const s = root.screen;
        if (!s)
            return Qt.size(0, 0);
        return Qt.size(Math.max(1, Math.round(s.width / root.xrayScale)), Math.max(1, Math.round(s.height / root.xrayScale)));
    }
    // output pixels per logical pixel, 0 until measured (see
    // XrayScaleProbe). Nothing bakes until it resolves - baking a whole
    // wallpaper folder at the wrong sigma and then again at the right one
    // is minutes of pointless work - but it always resolves, to 1 if the
    // measurement can't be made.
    property real xrayOutputScale: 0
    // Every output measured so far, by name. The launcher follows the
    // compositor's focused output (see LauncherWindow.syncScreen), so `screen`
    // changes whenever it opens on a different monitor - and a different output
    // can have a different fractional scale, which is the unit xraySigma is
    // expressed in, so the measurement has to be made again there. Remembering
    // it per output is what keeps moving *back* free: an unmeasured output
    // spends a probe (~500ms) with the backdrop dropped to the live-blur
    // fallback, since a scale of 0 is also what holds the bake back.
    property var xrayOutputScales: ({})
    onScreenChanged: root.xrayOutputScale = (root.screen ? root.xrayOutputScales[root.screen.name] : 0) ?? 0
    // the blur as it applies to the baked image rather than to the screen:
    // output pixels -> logical pixels -> the quarter-size image. 0 while the
    // scale is unknown, which is what holds the bake back.
    readonly property real xrayCacheSigma: root.xrayOutputScale > 0 ? root.xraySigma / root.xrayOutputScale / root.xrayScale : 0
    // The baked backdrop for the current wallpaper, or "" if there isn't one
    // yet (no ffmpeg, or a folder still being worked through), which
    // falls the launcher back to blurring live.
    readonly property string xrayBlur: {
        if (Settings.bgBlur !== "xray")
            return "";
        const w = root.list.find(x => x.path === Settings.currentWallpaper);
        return w ? w.blur : "";
    }
    // Everything the backdrop could draw, best first: the bake, or - until
    // there is one - the raw wallpaper for the launcher to blur live. That
    // fallback is only worth naming once a scan that was actually looking for
    // the current backdrops has come back without one (see scanKey); before
    // that it is just a full-size wallpaper decode that the bake replaces
    // moments later.
    readonly property string xrayWant: {
        if (Settings.bgBlur !== "xray")
            return "";
        if (root.xrayBlur !== "")
            return root.xrayBlur;
        return root.scanKey === root.xrayCacheKey ? root.matugenSource : "";
    }
    // What the backdrop actually draws, and whether that is the raw wallpaper
    // - i.e. whether the launcher has to blur it itself.
    property string xrayShown: ""
    property bool xrayShownLive: false
    function syncXrayShown() {
        // Only ever swapped while the launcher is down. Two things move it,
        // and neither is watchable mid-open:
        //
        //   - applying a wallpaper leaves the launcher open on the picker,
        //     where the tiles hide the backdrop, so the swap only shows as the
        //     UI fades out on the way to closing - which reads as the backdrop
        //     changing out from under the exit animation.
        //   - the output scale resolving (see XrayScaleProbe, ~1.4s after a
        //     daemon start, and later than that with Settings.preload on)
        //     re-keys every cache entry, walking xrayWant through "" and then
        //     a bake that still has to be decoded. An Image drops what it is
        //     showing the moment its source changes, so on a first open caught
        //     inside that window it is a backdrop-shaped hole under the reveal
        //     - measured 600ms of nothing at all, the decode being that slow
        //     against a first open's busy GUI thread.
        //
        // Drawing nothing is the one thing worse than swapping late, so an
        // empty backdrop takes whatever is going immediately: on a cold cache
        // the alternative is a whole first open with no backdrop at all. Same
        // for a backdrop nobody is looking at, which is what the mode being
        // off makes this.
        if (root.launcherShown && root.xrayShown !== "" && Settings.bgBlur === "xray")
            return;
        root.xrayShownLive = root.xrayWant !== "" && root.xrayBlur === "";
        root.xrayShown = root.xrayWant;
    }
    onXrayWantChanged: root.syncXrayShown()
    // Everything the baked files are named after. A new output geometry or
    // scale (or switching the mode on at all) changes every name, so the
    // scan has to run again to generate the new ones and sweep the old.
    readonly property string xrayCacheKey: (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR") ? "on" : "off")
        + "|" + root.xraySize.width + "x" + root.xraySize.height + "|" + root.xrayCacheSigma
    onXrayCacheKeyChanged: root.rescan()

    // Measures the output scale that xraySigma needs, once, off the device
    // pixel ratio of a mapped surface (see XrayScaleProbe). Only ever runs in
    // "xray" mode, and the surface it needs to exist on goes away the moment
    // the number lands. A compositor that never reports one just leaves the
    // timeout below to settle it at 1, i.e. logical pixels stand in for output
    // pixels, which is exactly right on an unscaled output.
    readonly property bool xrayScaleWanted: (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR"))
        && root.xrayOutputScale === 0 && root.screen !== null
    // `output` is the name of the output the measurement was taken on, which is
    // not necessarily the one in use by the time it lands: the probe settles on
    // a debounce (see XrayScaleProbe), and the launcher can move to another
    // monitor inside that window.
    function setXrayOutputScale(s, output) {
        // a bad measurement (a surface that never mapped, a screen that
        // resized mid-measure) must still resolve to something, or nothing
        // would ever bake
        const scale = s > 0.1 ? s : 1;
        // mutated in place deliberately - nothing binds to the map, it is only
        // ever read back on a screen change
        if (output)
            root.xrayOutputScales[output] = scale;
        // a measurement for an output that is no longer the one in use is worth
        // filing but not applying; the probe is already re-running against the
        // current one, and adopting this would bake the folder at its sigma
        if (!output || !root.screen || output === root.screen.name)
            root.xrayOutputScale = scale;
    }
    Timer {
        id: xrayScaleTimeout
        interval: 3000
        running: root.xrayScaleWanted
        onTriggered: root.setXrayOutputScale(1, root.screen ? root.screen.name : "")
    }
}
